--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pmmp/PocketMine-DevTools
projects:
  PocketMine-DevTools:
    path: ""
    stub: src/DevTools/ConsoleScript.php
    icon: devtools.png
    compressBuilds: false
...
